---

- name: Ensure network packages are present
  pacman: 
    name: "{{ item }}"
    state: present
  with_items:
    - ifplugd

- name: "Ensure ifplugd for {{ netctl_wired_interface }} is active"
  service: 
    name: "netctl-ifplugd@{{ netctl_wired_interface }}"
    state: started
    enabled: true
  when: netctl_wired_interface is defined

- include: configure_wifi.yml
  when: netctl_enable_wifi and netctl_wifi_interface is defined
